skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "B2uFRCTpLjVLSmG6CzVHYyfniFUAZbL1UppBAXLDHfQ2"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
